### ISSUE TITLE
Remove the comma from url permissions

### ISSUE THREAD

**Issue by philpott** [amzn/ads-pao-amznjs-gtm-template#10]
https://github.com/amzn/ads-pao-amznjs-gtm-template/blob/f5287018839c6ae37772902bb409cc4c518e2f7d/template.tpl#L647C17-L647C71

Scanning the template you should not include the comma on the url permissions.

**Comment by zgpalmer** [comment]
Closed for recent CR, removed comma and ensured only one url is there for permissions
